### ISSUE TITLE
How to pass maven/cljsjs dependencies to the lumo compiler

### ISSUE THREAD

**Issue by arichiardi** [nervous-systems/serverless-cljs-plugin#17]
Hi @moea!

A problem that it is probably also linked with https://github.com/anmonteiro/lumo/issues/239 is that there is no way at the moment to pass additional classpath entries to the lumo compiler.

So for instance, in a normal `lumo` script I would do:

```console
$ boot with-cp -d ... -d ... -w -f cp # dumps the resolved classpath to the cp file
```

or

```console
$ lein classpath > cp
```

and then:

```
$ lumo -c $(cat cp) .....other args...
```

This is necessary because Maven dependencies needs to be solved and passed in to `lumo` as "classpath". Node.js does not have any classpath of course, but this is how `lumo` has inherited dependency resolution from the Maven world.

Probably there is no clean solution at the moment and I am open to suggestions. In my code I try to avoid using Maven dependencies completely when using `lumo` but I thought it might be useful to write this down.

**Comment by moea** [comment]
I implemented the functionality locally to have the user specify maven deps / classpath entries in serverless.yml, but due to the issue you mentioned, I'm not sure it's currently useful.

**Comment by arichiardi** [comment]
I think `andare` should work...if you want to push a branch with the changes, I can have a look.

**Comment by moea** [comment]
It doesn't work, that's why I opened the issue against `lumo`.  To test, just invoke `serverless-lumo.build` against a project which requires andare, passing `-D andare:0.7.0` on the command line.

**Comment by arichiardi** [comment]
Oh good that you shared a repro you see, it might be a `-D` problem.

**Comment by arichiardi** [comment]
It would be awesome to have that feature btw, so that one could use `promesa`, for instance, instead of `core.async`. Promesa should be `lumo` compatible, I am trying as we speak.

**Comment by arichiardi** [comment]
Hi @moea, we fixed it!

So now that `andare` works, your patch for passing the classpath to the plugin would be awesome to have.
