### ISSUE TITLE
Failed to find base.js

### ISSUE THREAD

**Issue by arichiardi** [nervous-systems/serverless-cljs-plugin#24]
Hello @moea,
I am writing here because I need some help with the following error and maybe you know a bit better what is going on. I basically get:

```
{
  "errorMessage": "Cannot find module './out/goog/bootstrap/nodejs.js'",
  "errorType": "Error",
  "stackTrace": [
    "Function.Module._load (module.js:417:25)",
    "Module.require (module.js:497:17)",
    "require (internal/module.js:20:19)",
    "Object.<anonymous> (/var/task/index.js:1:63)",
    "Module._compile (module.js:570:32)",
    "Object.Module._extensions..js (module.js:579:10)",
    "Module.load (module.js:487:32)",
    "tryModuleLoad (module.js:446:12)",
    "Function.Module._load (module.js:438:3)"
  ]
}
```

If I invoke the deployed lambda. My configuration is the default:

```
{:source-paths ["src"]
 :compiler {:language-in :ecmascript5
            :optimizations :none
            :source-map false
            :verbose true}}
```

I checked, and the file is in `out`. Any hint is appreciated :smile: Maybe I am missing some AWS configuration?

**Comment by moea** [comment]
In your zip file you have an index.js, and there's a sibling directory called `out` which has the right files in it?  What happens if you unzip the deployed zip file locally, in a temporary directory, and run `node index.js`?  If the project is up somewhere, I'm happy to look at it.

**Comment by moea** [comment]
Is this the same issue as the PR you opened about directories not having the executable bit set?  I could see that affecting this, maybe.

**Comment by arichiardi** [comment]
Yep. I am debugging hard, seems like permissions are not set when I execute the `lumo` build script from inside `sls deploy` (I know it does not make sense, still digging). If I launch it manually the permissions are set correctly to `755`.

**Comment by arichiardi** [comment]
Oh, there is a bug, but it is in `applyZipExclude`, where it seems `JSZip` does not set permissions properly :man_facepalming:
