### ISSUE TITLE
Serverless plugin "serverless-cljs-plugin" not found

### ISSUE THREAD

**Issue by JimTheMan** [nervous-systems/serverless-cljs-plugin#32]
I just scaffolded out a project and ran "serverless deploy". I get this error: 

Serverless Error ---------------------------------------
 
  Serverless plugin "serverless-cljs-plugin" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.9.1
     Serverless Version:     1.24.0

**Comment by moea** [comment]
You're using the leiningen template?  You need to install the plugin via `lein npm install` or `lein deps`, as template creation adds it to your project.clj, but can't install it - it can only generate files.

**Comment by Lokeh** [comment]
Please add this to the README ^

**Comment by moea** [comment]
The suggestion to run `lein deps` is in the generated README, it'll go out in the next release.
