### ISSUE TITLE
`serverless deploy` does not work and I don't see instructions for fixing it?

### ISSUE THREAD

**Issue by jakubholynet** [nervous-systems/serverless-cljs-plugin#36]
After executing 

```shell
npm install -g serverless
npm install -g serverless-cljs-plugin
lein new serverless-cljs myapp
cd myapp
```

and changing the config to `runtime: node6.10` I want to run

    serverless deploy

but it fails with

```
  Serverless Error ---------------------------------------

  Serverless plugin "serverless-cljs-plugin" not found. Make sure it's installed and listed in the "plugins" section of your serverless config file.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.10.0
     Serverless Version:     1.25.0
```

I have no idea why. Any idea? Have I missed some setup step?

**Comment by jakubholynet** [comment]
**RESOVED**: I installed serverless (and the plugin) again, this time without `-g`, and it started working. This setup should perhaps be clearly documented in the docs (or have I just overlooked it?!)

Thank you!

**Comment by jakubholynet** [comment]
Ok but shouldnt the Readme be inproved?
fre. 19. jan. 2018 kl. 15:24 skrev Moe Aboulkheir <notifications@github.com

**Comment by moea** [comment]
I'm happy to accept a pull request if you think that makes sense, but it's a serverless plugin that is installed in the same manner as all plugins - typically with a package.json managed by the user.  If you created your project via the Leiningen template, the documentation around that has been improved slightly and will result in a clearer generated README in the next release.
